name: first
on: push
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step2
        run: echo "$(date +%Y-%m-%d_%H-%M-%S)"
  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step2
        run: echo "$(date +%Y-%m-%d_%H-%M-%S)"
  job3:
    name: job3
    runs-on: macos-latest
    needs: [job1, job2]
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step2
        run: echo "$(date +%Y-%m-%d_%H-%M-%S)"
