name: first
on: push
jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: first step
        uses: actions/checkout@v2
      - name: second step
        run: 
          echo '`r format(Sys.Date(), "%B %d, %Y")`'